### ISSUE TITLE
About the generated Python code

### ISSUE THREAD

**Issue by CLL112** [EMI-Group/tensorneat#24]
After converting the network into formulas or Python code, I noticed that some hidden neurons are being referenced before they are computed, which is quite strange. For example:  
```python
h[0] = 0.171989*h[31] + 3.169343*i[0] - 0.266712
```
Here, `h[31]` has not been calculated yet, so it will use its initial value of 0. Is this normal?
```
Python Code:
h = np.zeros(35)
o = np.zeros(2)
h[0] = 0.171989*h[31] + 3.169343*i[0] - 0.266712
h[1] = -sin(0.112585*h[28] + 2.851631*i[0] - 2.619233*i[1] - 0.026671)
h[2] = -tanh(1.154439*i[0] + 1.897031*i[1] + 0.352859)
h[3] = nan
h[4] = 1.742897*h[0] - 0.302724*h[9] + 0.276833
h[5] = -0.297971*h[15] - 0.757493*h[24] + 2.0499*i[1] + 0.916681
h[6] = -tanh(2.076261*h[23]*i[1] - 1.89432)
h[7] = -2.081779*i[0] - 1.563756*i[1] + 0.980241
h[8] = 0.156715*h[17] - 1.694074*i[0] + 1.365514*i[1] + 1.311888
h[9] = tanh(0.619051*h[18] + 0.330781)
h[10] = 0.816805*h[11]
h[11] = -sin(0.300976*h[2] + 0.627619)
h[12] = 0.34393 - 0.560032*h[33]
h[13] = tanh(0.00587*h[17]*h[26]*i[1] + 0.874081)
h[14] = Max(0, 0.415834*i[0] + 0.395707*i[1] + 1.267994)
h[15] = Piecewise((-0.703819*i[1] - 0.186702, 0.703819*i[1] + 0.186702 < 0), (-0.003519*i[1] - 0.000934, True))
h[16] = -1.23256*i[0] + 0.079172*i[1] - 1.614457
h[17] = Max(0, 0.065526*h[18] + 0.09237*h[19] + 0.128332*i[1] + 0.361111)
h[18] = 0.432082*h[1] + 0.151905*h[26] + 0.444149*i[0] - 0.605303*i[1] + 0.5776
h[19] = Piecewise((0.913525*i[0] + 0.164543, 0.913525*i[0] + 0.164543 > 0), (0.004568*i[0] + 0.000823, True))
h[20] = -sin(0.129024*h[15] + 0.163934)
h[21] = 1.007134
h[22] = -tanh(-0.495377*h[15] + 0.06355*h[25] + 0.633176)
h[23] = Max(0, 0.715448*h[19] - 0.11983*h[27] - 0.359031)
h[24] = tanh(1.849501*i[0] + 0.141925)
h[25] = Max(0, 0.411862*h[26]*i[0] + 0.304906)
h[26] = 0.172775
h[27] = Max(0, 1.272269*h[24] + 0.399686)
h[28] = -0.110427
h[29] = -0.000292
h[30] = Piecewise((0.59178*h[10] - 0.154874*h[25] - 0.082747, -0.59178*h[10] + 0.154874*h[25] + 0.082747 < 0), (0.002959*h[10] - 0.000774*h[25] - 0.000414, True))
h[31] = Piecewise((0.856304*i[1] + 0.125001, 0.856304*i[1] + 0.125001 > 0), (0.004282*i[1] + 0.000625, True))
h[32] = Max(0, 0.781773*h[28] - 0.127448)
h[33] = tanh(1.0*h[2] + 0.008956)
h[34] = 0.891857*h[8]
o[0] = tanh(0.121949*h[1] + 0.020327*h[12] + 0.031256*h[13] + 0.070328*h[14] + 0.006741*h[17] + 0.030249*h[20] + 0.069293*h[4] - 0.083061*h[5] + 0.146785*h[6] - 0.09403*h[7] - 0.281119*h[8] + 0.310527)
o[1] = tanh(0.071067*h[0] + 0.093137*h[1] + 0.167901*h[13] + 0.038465*h[14] + 0.00907*h[17] + 0.064836*h[22] + 0.116218*h[32] - 0.0562*h[34] + 0.269817*h[5] - 0.012843*h[6] - 0.146425*h[7] - 0.115288)
```

**Comment by WLS2002** [comment]
That is so strange. Please provide the running config for me to test.

**Comment by CLL112** [comment]
Here is my config file:
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "4"
import jax.numpy as jnp

from tensorneat.pipeline import Pipeline
from tensorneat.algorithm.neat import NEAT
from tensorneat.genome import DefaultGenome, BiasNode, DefaultMutation
from tensorneat.problem.func_fit import CustomFuncFit
from tensorneat.common import ACT, AGG
from tensorneat.problem.func_fit import custom2
import jax
import pickle

if __name__ == "__main__":

    pipeline = Pipeline(
        algorithm=NEAT(
            pop_size=1000,
            species_size=20,
            survival_threshold=0.03,
            min_species_size=2,
            genome=DefaultGenome(
                num_inputs=2,
                num_outputs=2,
                max_nodes=100,
                max_conns=250,
                init_hidden_layers=(50,),
                mutation=DefaultMutation(
                    node_add=0.8,  # default is 0.1
                    node_delete=0.4,
                    conn_add=0.8,  # default is 0.2
                    conn_delete=0.4,
                ),
                node_gene=BiasNode(
                    activation_options=[ACT.lelu, ACT.tanh, ACT.sin, ACT.relu,ACT.identity],
                    aggregation_options=[AGG.sum, AGG.product, AGG.mean],
                ),
                output_transform=ACT.tanh,
            ),
        ),
        problem=custom2(),
        generation_limit=100000,
        fitness_target=-1e-6,
        seed=45,
        is_save=True
    )

    # initialize state
    state = pipeline.setup()
    # run until terminate
    state, best = pipeline.auto_run(state)
    # show result
    pipeline.show(state, best)

    # visualize the best individual
    network = pipeline.algorithm.genome.network_dict(state, *best)
    print(pipeline.algorithm.genome.repr(state, *best))
    pipeline.algorithm.genome.visualize(network, save_path="./xor_network_41.svg")

    # best is a tuple (nodes, conns) of jax array
    best = jax.device_get(best)  # convert best to numpy array on cpu
    with open("best.pkl", "wb") as f:
        pickle.dump(best, f)

    # Convert to mathematical formula
    from tensorneat.common.sympy_tools import to_latex_code, to_python_code

    sympy_res = pipeline.algorithm.genome.sympy_func(
        state,
        network,
        sympy_output_transform=ACT.obtain_sympy(ACT.tanh)
    )

    print("\nLatex Formula:")
    latex_code = to_latex_code(*sympy_res)
    print(latex_code)

    print("\nPython Code:")
    python_code = to_python_code(*sympy_res)
    print(python_code)

```
Here is the best individual  saved after 514 iterations. I also found that it exhibits the same phenomenon:  
`h[3] = -sin(0.580582*h[22]*i[0]*i[1] - 0.469189)`：
```
Python Code:
h = np.zeros(75)
o = np.zeros(2)
h[0] = Max(0, -0.393324*i[1] - 0.304097)
h[1] = -tanh(0.520576*i[1] - 0.621616)
h[2] = Max(0, -0.595404*i[0]*i[1] - 0.476)
h[3] = -sin(0.580582*h[22]*i[0]*i[1] - 0.469189)
h[4] = tanh(0.303605*i[1] + 1.490881)
h[5] = 0.540493*h[16] - 0.527148
h[6] = -sin(1.456117*h[28] + 0.907768*h[42] + 1.714789)
h[7] = -sin(0.897136*h[50] - 0.793472*h[60] + 0.56405*i[0] - 0.260179)
h[8] = Piecewise((-0.207455*i[0]*i[1] + 1.305145, 0.207455*i[0]*i[1] - 1.305145 < 0), (-0.001037*i[0]*i[1] + 0.006526, True))
h[9] = Piecewise((2.485227*h[21] + 0.562212*i[0] + 0.153083, 2.485227*h[21] + 0.562212*i[0] + 0.153083 > 0), (0.012426*h[21] + 0.002811*i[0] + 0.000765, True))
h[10] = Max(0, 0.100386*h[45] - 0.374037)
h[11] = -1.455953*i[0] + 0.32391*i[1] + 0.03569
h[12] = -sin(1.031857*i[0]*i[1] + 0.434128)
h[13] = -0.029788*h[18] + 4.036304*i[0] + 1.445527*i[1] - 0.86662
h[14] = 2.668357
h[15] = sin(0.058248*h[63] + 0.025396)
h[16] = Piecewise((1.602*i[1] - 0.355662, 1.602*i[1] - 0.355662 > 0), (0.00801*i[1] - 0.001778, True))
h[17] = Piecewise((0.246702*h[45] - 0.087146*i[0] + 2.860729*i[1] + 1.412821, 0.246702*h[45] - 0.087146*i[0] + 2.860729*i[1] + 1.412821 > 0), (0.001234*h[45] - 0.000436*i[0] + 0.014304*i[1] + 0.007064, True))
h[18] = tanh(0.047125*h[34] + 0.534341*h[62] + 1.906155)
h[19] = Piecewise((-0.43377*h[59] + 0.478223*i[0] - 0.824897*i[1] - 0.637511, 0.43377*h[59] - 0.478223*i[0] + 0.824897*i[1] + 0.637511 < 0), (-0.002169*h[59] + 0.002391*i[0] - 0.004124*i[1] - 0.003188, True))
h[20] = Piecewise((0.10993*i[0]*i[1] + 3.083846, 0.10993*i[0]*i[1] + 3.083846 > 0), (0.00055*i[0]*i[1] + 0.015419, True))
h[21] = Max(0, 1.13565*i[1] + 0.569425)
h[22] = Piecewise((1.061129*i[1] + 0.941416, 1.061129*i[1] + 0.941416 > 0), (0.005306*i[1] + 0.004707, True))
h[23] = sin(0.516021*h[46] + 0.112596)
h[24] = Max(0, 0.128278*h[37] - 0.668598*h[61] - 0.326777*i[0] + 0.351653)
h[25] = Piecewise((-0.15701*h[26] + 0.286644*h[55] + 1.529387*i[0] - 0.390395, 0.15701*h[26] - 0.286644*h[55] - 1.529387*i[0] + 0.390395 < 0), (-0.000785*h[26] + 0.001433*h[55] + 0.007647*i[0] - 0.001952, True))
h[26] = sin(0.282044*h[29] - 0.59717*h[39] - 0.009626*i[1] + 0.116546)
h[27] = -2.448874*i[0] + 1.027433*i[1] + 0.020469
h[28] = sin(1.571725*i[1] - 0.073324)
h[29] = Piecewise((1.13804*i[0] - 0.587174*i[1] - 0.079896, -1.13804*i[0] + 0.587174*i[1] + 0.079896 < 0), (0.00569*i[0] - 0.002936*i[1] - 0.000399, True))
h[30] = -sin(0.642609*h[1] + 0.182434*i[0] - 1.507243)
h[31] = -0.355151*i[0] - 1.823967*i[1] - 0.174811
h[32] = 1.426471*h[74] - 1.467207*i[1] + 1.084125
h[33] = Max(0, 0.242858*h[53] + 0.178815*i[0] - 0.347632)
h[34] = -tanh(0.030547*h[53] + 0.220346*i[0] + 0.453322*i[1] - 0.189637)
h[35] = Max(0, -0.11602*i[0] + 0.435637*i[1] + 1.69347)
h[36] = tanh(0.480057*i[1] + 0.673986)
h[37] = -sin(0.008656*h[15]*i[0] + 0.31275)
h[38] = sin(0.547461*h[18] + 0.756188)
h[39] = -tanh(0.445631*i[0] + 1.345173)
h[40] = Piecewise((-0.063427*i[0] - 1.473829*i[1] + 1.399987, 0.063427*i[0] + 1.473829*i[1] - 1.399987 < 0), (-0.000317*i[0] - 0.007369*i[1] + 0.007, True))
h[41] = 1.138754*h[44]
h[42] = -0.566675*h[69] + 1.201686*i[0] - 0.659911
h[43] = 0.173262*i[0] + 1.062508*i[1] + 0.003131
h[44] = -3.692652*i[0] + 2.149998*i[1] - 0.960821
h[45] = Max(0, 0.04869*h[14]*h[35]*i[0]*i[1] + 1.542186)
h[46] = Max(0, 0.955812*h[38] + 0.311495*h[43] - 0.320291*h[57] + 0.095745)
h[47] = Max(0, 1.184057*i[0]*i[1] + 1.205099)
h[48] = 0.030837*h[0] - 0.034122*h[11] - 0.0403*h[12] + 0.084885*h[13] + 0.012358*h[2] - 0.03802*h[20] + 0.004205*h[24] + 0.010416*h[25] - 0.04639*h[26] - 0.039131*h[27] + 0.062182*h[29] + 0.008632*h[3] + 0.044204*h[30] + 0.022793*h[31] + 0.033977*h[32] + 0.010851*h[33] + 0.040114*h[35] + 0.029336*h[36] - 0.011805*h[4] + 0.018999*h[40] + 0.012516*h[42] - 0.036528*h[43] - 0.099854*h[44] + 0.009396*h[45] - 0.018849*h[47] - 0.040753*h[6] - 0.008106*h[7] - 0.002093*h[8] + 0.011688*h[9] - 0.006355*o[0] - 0.097498
h[49] = 0.034605*h[0] + 0.002957*h[10] - 0.017802*h[11] + 0.009935*h[12] + 0.034486*h[13] + 0.064219*h[17] - 0.051131*h[19] + 0.015014*h[2] + 0.015692*h[25] - 0.023338*h[26] - 0.076808*h[29] - 0.052635*h[3] + 0.034495*h[30] - 0.042703*h[31] + 0.024121*h[33] - 0.036367*h[34] - 0.046071*h[35] + 0.020079*h[36] + 0.028127*h[37] + 0.05134*h[4] - 0.062171*h[40] - 0.010527*h[42] + 0.061489*h[43] + 0.000863*h[47] + 0.01156*h[51] + 0.041673*h[54] - 0.0104*h[58] + 0.00494*h[6] - 0.043513*h[64] + 0.016655*h[68] - 0.046844*h[7] - 0.012324*h[70] + 0.018825*h[72] - 0.032468*h[8] + 0.122626*h[9] + 0.027858*o[0] - 0.01174*o[1] - 0.05737
h[50] = 1.221238*i[1] - 0.079136
h[51] = sin(1.595441*h[27] - 0.666129)
h[52] = sin(0.232478*i[0] + 0.302679)
h[53] = tanh(0.847736*i[1] + 0.705066)
h[54] = -sin(1.556384*h[73] - 1.454493)
h[55] = Max(0, 0.051253 - 0.48735*i[1])
h[56] = Piecewise((0.56021*h[14] - 0.50237*h[22] + 0.130264*i[0] + 1.566567, 0.56021*h[14] - 0.50237*h[22] + 0.130264*i[0] + 1.566567 > 0), (0.002801*h[14] - 0.002512*h[22] + 0.000651*i[0] + 0.007833, True))
h[57] = 0.639292
h[58] = Max(0, -0.178051*h[32] - 0.782553)
h[59] = Piecewise((-0.076266*h[39]*i[1] - 1.044595, 0.076266*h[39]*i[1] + 1.044595 < 0), (-0.000381*h[39]*i[1] - 0.005223, True))
h[60] = Piecewise((0.110081*h[59] - 0.098415, 0.110081*h[59] - 0.098415 > 0), (0.00055*h[59] - 0.000492, True))
h[61] = Piecewise((-0.770219*h[60] - 0.565254, 0.770219*h[60] + 0.565254 < 0), (-0.003851*h[60] - 0.002826, True))
h[62] = 0.619035*h[56] + 0.128363*h[67] + 0.217896
h[63] = Max(0, 0.705778*i[1] - 0.004013)
h[64] = 0.774546*h[71] - 0.385223
h[65] = sin(1.895392*i[1] + 0.172721)
h[66] = Piecewise((0.624749*h[65] + 1.196715, 0.624749*h[65] + 1.196715 > 0), (0.003124*h[65] + 0.005984, True))
h[67] = 0.135646
h[68] = 0.965753*h[24] + 0.050607
h[69] = -sin(0.90383*i[1] - 0.490802)
h[70] = 1.396789*h[46] + 0.015194
h[71] = -0.084691
h[72] = 1.0*h[14]
h[73] = 1.0*h[41]
h[74] = 1.0*i[0] + 0.076165
o[0] = -tanh(0.452189*i[0]*i[1] + 0.286043)
o[1] = tanh(0.594063*h[47] - 0.356644*i[0] + 0.224704)
```
In addition, when I load the best individual from a later generation, such as the best individual from generation 1500, a nan error occurs. However, the NEAT algorithm is still running well during iterations. Why does this issue occur when loading the best individual?
```
Traceback (most recent call last):
  File "/home/longchen/tensorneat/examples/func_fit2/visual.py", line 80, in <module>
    sympy_res = pipeline.algorithm.genome.sympy_func(
  File "/home/longchen/tensorneat/src/tensorneat/genome/default.py", line 206, in sympy_func
    nodes_exprs[symbols[i]], a_s = self.node_gene.sympy_func(
  File "/home/longchen/tensorneat/src/tensorneat/genome/gene/node/bias.py", line 181, in sympy_func
    z = ACT.obtain_sympy(node_dict["act"])(z)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/function.py", line 466, in __new__
    result = super().__new__(cls, *args, **options)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/function.py", line 307, in __new__
    evaluated = cls.eval(*args)
  File "/home/longchen/tensorneat/src/tensorneat/common/functions/act_sympy.py", line 47, in eval
    **return sp.Piecewise((z, z > 0), (leaky * z, True))**
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/decorators.py", line 236, in _func
    return func(self, other)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/expr.py", line 360, in __gt__
    return StrictGreaterThan(self, other)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/relational.py", line 843, in __new__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison
```

**Comment by CLL112** [comment]
Thank you for your reply. To facilitate loading historical best individuals, I modified the `pipeline`'s `analysis` saving method. This should be correct?
```
def analysis(self, state, pop, fitnesses):
       .......
        if self.is_save:
            # save best
            best_genome = jax.device_get((pop[0][max_idx], pop[1][max_idx]))
            file_name = os.path.join(self.genome_dir, f"{generation}.pkl")
            # with open(file_name, "wb") as f:
            #     np.savez(
            #         f,
            #         nodes=best_genome[0],
            #         conns=best_genome[1],
            #         fitness=self.best_fitness,
            #     )
            # best = jax.device_get(best)  # convert best to numpy array on cpu
            with open(file_name, "wb") as f:
                pickle.dump(best_genome, f)
     ........
```

**Comment by WLS2002** [comment]
It is indeed a bug and I have already fixed it! Please re-install and try again. Thank you for your support to TensorNEAT!

**Comment by CLL112** [comment]
Thank you very much, but I still have an issue — when generating the formulas for some individuals, an error occurs with `NaN` values.
```
Traceback (most recent call last):
  File "/home/longchen/tensorneat/examples/func_fit2/visual.py", line 80, in <module>
    sympy_res = pipeline.algorithm.genome.sympy_func(
  File "/home/longchen/tensorneat/src/tensorneat/genome/default.py", line 206, in sympy_func
    nodes_exprs[symbols[i]], a_s = self.node_gene.sympy_func(
  File "/home/longchen/tensorneat/src/tensorneat/genome/gene/node/bias.py", line 181, in sympy_func
    z = ACT.obtain_sympy(node_dict["act"])(z)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/function.py", line 466, in __new__
    result = super().__new__(cls, *args, **options)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/function.py", line 307, in __new__
    evaluated = cls.eval(*args)
  File "/home/longchen/tensorneat/src/tensorneat/common/functions/act_sympy.py", line 47, in eval
    **return sp.Piecewise((z, z > 0), (leaky * z, True))**
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/decorators.py", line 236, in _func
    return func(self, other)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/expr.py", line 360, in __gt__
    return StrictGreaterThan(self, other)
  File "/home/longchen/miniconda3/envs/neat/lib/python3.10/site-packages/sympy/core/relational.py", line 843, in __new__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison
```
When I change the `forward` function of the faulty activation function to `return x`, I find that the issue is usually caused by the first few generated node values being `nan`.
```
Python Code:
h = np.zeros(83)
o = np.zeros(2)
h[5] = -0.052804
**h[38] = nan**
h[57] = 0.642575
**h[67] = nan**
h[72] = 0.513136
h[75] = 0.981454
o[0] = tanh(0.429377*i[0] + 0.52406*i[1] - 0.219799)
h[1] = -0.245492*i[1] - 0.559445
h[2] = 0.424013*i[0]*i[1] - 0.512945
h[3] = 0.171796*i[0] - 0.556728*i[1] + 0.3537
h[4] = -0.443455*i[0]*i[1] + 1.497627
h[8] = -1.360914*i[0] + 0.26604*i[1] + 0.191714
h[11] = sin(-2.091658*i[0] + 0.3995*i[1] + 0.600933)
h[12] = -0.396824*i[0] + 0.17315*i[1] + 1.303732
h[14] = 1.0*h[67]
h[21] = 0.435766*i[1] + 0.472511
h[27] = -0.712874*i[0] - 0.495742
h[28] = sin(1.460719*i[1] - 0.24362)
h[29] = -0.19752*i[0] - 0.254908*i[1] - 0.106494
h[31] = -tanh(0.141044*i[0] + 1.775136*i[1] + 0.36485)
h[32] = -0.454434*i[0] - 1.151417*i[1] + 0.674136
h[35] = -sin(0.288719*i[0] + 0.803896*i[1] - 1.166888)
h[36] = 0.926941*i[1] + 0.281859
h[40] = 0.023819*i[0] - 2.563115*i[1] + 1.459887
h[43] = 1.129956*i[0] + 1.867276*i[1] + 0.144179
h[44] = -4.191634*i[0] + 1.579335*i[1] - 0.383226
h[47] = -0.652353*h[75] + 2.009886*i[0] + 0.225796*i[1] - 0.060314
h[50] = 0.655507*i[1] - 0.189952
h[52] = -0.147537*h[72]*i[0] - 0.252661
h[53] = sin(1.03652*i[1] + 1.253294)
h[55] = sin(0.523939*i[1] + 0.013736)
h[56] = -tanh(0.647628*i[0] - 0.830922)
h[63] = -0.760447*i[1] - 1.948519
h[69] = 0.081852 - 1.720639*i[1]
h[70] = 1.0*h[38] - 0.09633
h[73] = 0.68243*i[1] - 0.053929
h[74] = -1.312601*i[1] - 0.050778
h[13] = 1.736833*h[73] + 3.475738*i[0] - 1.066896
h[15] = 2.794257*h[63] + 1.301596
h[22] = 1.041002*h[74] - 0.305383
h[25] = -sin(1.040145*h[55] + 1.844719)
h[30] = 1.815945*h[1]*i[0] + 1.418536
h[33] = 0.987256*h[53]*i[0] - 0.520329
h[34] = tanh(0.998788*h[53] + 0.735281*i[0] - 1.43406*i[1] + 0.510802)
h[39] = sin(0.195217*h[40]*i[0] + 0.080745)
h[41] = 0.662652*h[44] - 0.211234
h[42] = -1.61414*h[69] - 0.082936*h[72] + 1.610071*i[0] - 0.52406
h[46] = 0.086345*h[43] - 0.271526*h[57] + 0.244069*h[70] - 0.083041
h[51] = 1.626549*h[27] + 0.30748
h[58] = 1.071474*h[56] - 0.017977
h[64] = 1.306868*h[43] + 0.665303
h[71] = 0.965996*h[47] - 0.173041
h[79] = 1.00188*h[36]
h[80] = 0.462743 - 0.828579*h[31]
h[82] = 0.944536*h[3] - 0.282159
o[1] = tanh(0.45328*h[71] - 0.995943*i[0] + 0.058798)
h[26] = 0.860774*h[34] - 0.319913
h[37] = -tanh(0.304758*h[15] + 1.182739*i[0] + 0.685101)
h[54] = sin(1.520915*h[41] + 0.83524)
h[59] = 1.557329*h[39]*i[1] - 0.515575
h[62] = 0.398659*h[14] - 0.991241*h[58] - 0.866367
h[65] = 0.04128*h[42] + 0.547425*i[1] - 1.317257
h[76] = 1.278675*h[25] + 0.445822
h[78] = 0.21301*h[82] - 0.107387
h[81] = 0.924417*h[33] - 0.020344
h[0] = tanh(0.514568*h[59]*i[1] - 0.195821)
h[6] = -sin(1.294495*h[28] + 1.351636*h[42] - 0.464762*o[1] + 1.143229)
h[9] = 1.75279*h[21] + 0.640222*h[54] - 0.287071*h[56] + 0.687091*i[0] + 0.198053
h[19] = -sin(-1.563798*h[59] + 0.932974*i[0] + 0.073652*i[1] + 0.76119)
h[20] = 0.649488*h[22]*h[27]*i[0]*o[1] + 3.558526
h[23] = -0.197316*h[46]*h[54] + 0.418702
h[60] = 0.407264*h[59] - 0.004924
h[77] = 0.956375*h[26] + 0.324365
h[7] = -sin(0.027146*h[50]*h[60]*i[0] + 0.298587)
h[16] = 0.950208*h[9] - 0.308087
h[18] = 0.138253
h[61] = 0.860832 - 1.601575*h[60]
h[24] = 1.62276*h[37]*h[61]*i[0] - 0.16833
h[45] = tanh(1.66534*h[18]*i[0]*i[1] + 1.131848)
h[10] = 0.080952*h[45]*o[1] - 0.391998
h[17] = 0.806623*h[45] - 0.410568*i[0] + 2.312075*i[1] + 1.357916
h[48] = 0.058589*h[0] - 0.016585*h[12] + 0.109061*h[13] + 0.039001*h[2] - 0.033365*h[20] + 0.020796*h[23] - 0.022747*h[24] + 0.048316*h[25] - 0.036998*h[27] + 0.04974*h[29] + 0.043351*h[30] + 0.046492*h[32] + 0.029253*h[33] + 0.044255*h[35] + 0.032847*h[4] + 0.010767*h[40] - 0.034032*h[42] - 0.040208*h[43] - 0.144269*h[44] + 0.031318*h[45] + 0.032753*h[47] - 0.063265*h[6] - 0.009671*h[7] + 0.018715*h[78] + 0.012476*h[79] - 0.020222*h[8] - 0.013831*h[80] + 0.069409*h[9] - 0.004067*o[0] - 0.016491
h[68] = -0.448209
h[49] = 0.00237*h[0] - 0.001594*h[10] + 0.010374*h[11] + 0.026331*h[12] + 0.071027*h[13] + 0.165107*h[16] + 0.0786*h[17] - 0.084129*h[19] - 0.107403*h[29] - 0.016015*h[3] - 0.024895*h[30] - 0.072011*h[35] + 0.040803*h[36] + 0.038442*h[37] + 0.062023*h[4] - 0.100208*h[40] - 0.015513*h[42] + 0.00612*h[47] - 0.069744*h[51] + 0.000773*h[54] + 0.023279*h[6] + 0.080606*h[64] + 0.045874*h[7] + 0.019967*h[72] + 0.037247*h[76] + 0.059564*h[8] - 0.044619*h[81] + 0.033209*o[0] - 0.019919*o[1] - 0.114961
h[66] = 0.107958*h[3]*h[48]*h[65] + 0.059296
```

**Comment by WLS2002** [comment]
Hi, sorry for the late reply. I was busy recently and just got a chance to fix the issue.

Thank you for your patience, and thanks again for reporting it. Let me know if anything else comes up.
